apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: python-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Hojip-Kim/CI-CD-Pipeline-Deployments.git
    targetRevision: main
    path: charts/python-app
  destination:
    server: https://kubernetes.default.svc
    namespace: python
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 3
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
