replicaCount: 1
image:
  repository: hojipkim/python-app
  pullPolicy: IfNotPresent
  tag: '1f311f'
rollout:
  enabled: true
  imagePullPolicy: Always
  strategy:
    activeService: 'python-app'
    previewService: 'python-app-preview'
  autoPromotionEnabled: false
imagePullSecrets: []
nameOverride: ''
fullnameOverride: ''
serviceAccount:
  create: false
  automount: true
  annotations: {}
  name: ''
podAnnotations: {}
podLabels: {}
podSecurityContext: {}
securityContext: {}
service:
  type: ClusterIP
  port: 5000
ingress:
  enabled: true
  className: 'nginx'
  annotations: {}
  hosts:
    - host: python-app.test.com
      paths:
        - path: /
          pathType: Prefix
  tls: []
resources: {}
livenessProbe:
  httpGet:
    path: /api/v1/healthz
    port: http
readinessProbe:
  httpGet:
    path: /api/v1/healthz
    port: http
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
volumes: []
volumeMounts: []
nodeSelector: {}
tolerations: []
affinity: {}
