
{{- if .Values.rollout.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{ include "python-app.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "python-app.name" . }}
spec:
  revisionHistoryLimit: 6
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "python-app.name" . }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "python-app.name" . }}

    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.service.port }}
  strategy:
    blueGreen:
      activeService: {{ .Values.rollout.strategy.activeService | quote }}
      previewService: {{ .Values.rollout.strategy.previewService | quote }}
      {{- if not .Values.rollout.autoPromotionEnabled }}
      autoPromotionEnabled: true
      # 우선순위없는 기본 대기 30분
      scaleDownDelay: 30m    
      # 프로모션 뒤에는 1시간 대기
      scaleDownDelayAfterPromotion: 1h
      # 롤백 뒤에는 5분만 대기
      scaleDownDelayAfterRollback: 5m
      
      {{- end }}
{{- end }}
