apiVersion: v1
kind: Service
metadata:
  name: { { .Values.rollout.strategy.previewService | quote } }
  labels:
    app.kubernetes.io/name: { { include "python-app.name" . } }
spec:
  selector:
    app.kubernetes.io/name: { { include "python-app.name" . } }
  ports:
    - port: { { .Values.service.port } }
      targetPort: { { .Values.service.port } }
      protocol: TCP
      name: http
