{{- if .Values.rollout.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.rollout.strategy.activeService | quote }}
  labels:
    app.kubernetes.io/name: {{ include "python-app.name" . }}
spec:
  selector:
    app.kubernetes.io/name: {{ include "python-app.name" . }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
{{- end }}